variables:
  JAVA_HOME: 'c:\\java\\jdk1.8.0_172'  
  ANT_HOME: 'c:\\java\\apache-ant-1.10.4'
  MAVEN_HOME: 'c:\\java\\apache-maven-3.5.2'
  
before_script:
  - set PATH=%JAVA_HOME%\\bin;%ANT_HOME%\\bin;%MAVEN_HOME%\\bin;%PATH%
 
stages:
  - testCore
  - testSamples
  
testCore:
  stage: testCore
  script:
    - echo "Running Maven on Core packages..."
    - cd gocwebtemplate-core
    - mvn --batch-mode test 

testSamples:
  stage: testSamples
  script:
    - echo "Running Maven on Sample packages..."
    - cd gocwebtemplate-sample-jsf
    - mvn --batch-mode test 
    - cd ..\\gocwebtemplate-sample-jsp
    - mvn --batch-mode test 
