build_default:
  stage: build
  extends: 
    - .maven_repo_cache
    - .java_job
  script:
    - Invoke-Expression ('mvn ' + $env:MAVEN_CLI_OPTS + ' --file "$env:MAVEN_PROJECT_FILE" clean compile')
    - if ($lastexitcode -ne 0) {throw "Shell command failed"}
  artifacts:
    expire_in: 1 hour
    paths:
      - .\**\target
      # Adding the following two lines for the test job to have even when prepare does not run
      - builds/build.properties
      - .\**\pom.xml
