test_default:
  stage: test
  extends: 
    - .maven_repo_cache
    - .java_job
  dependencies:
    - build_default
  script:
    - Invoke-Expression ('mvn ' + $env:MAVEN_CLI_OPTS + ' --file "$env:MAVEN_PROJECT_FILE" test')
    - if ($lastexitcode -ne 0) {throw "Shell command failed"}
  artifacts:
    reports:
      junit: .\**\target\surefire-reports\TEST-*.xml
